# :two: Qualité du code

## Enjeux

- D'une vision utilitariste du code à une vision du code comme [**outil de communication**]{.orange}

- Favoriser la [**lisibilité**]{.orange} et la [**maintenabilité**]{.orange}

- Faciliter la [**réutilisation**]{.orange}

## Principes généraux

- Adopter les [**standards communautaires**]{.orange}

- Utiliser des [**fonctions**]{.orange}

- [**(Auto-)documenter**]{.orange} son code

## :one: Standards communautaires

> *"Good coding style is like correct punctuation: you can manage without it, butitsuremakesthingseasiertoread"*
>
> [Tidyverse Style Guide (R)](https://style.tidyverse.org/)

- [**Python**]{.blue2} : [PEP8](https://peps.python.org/pep-0008/), [PEP 257](https://peps.python.org/pep-0257/)
    - Des règles *opinionated*, mais [**conventionnelles**]{.blue2}

- La [**cohérence intra-projet**]{.orange} doit toujours primer

## :one: Standards communautaires - Outils {.smaller}

- [**Linters**]{.blue2} : diagnostic de qualité du code
    - [Pylint](https://github.com/PyCQA/pylint)

- [**Formatters**]{.blue2} : application automatique des standards
    - [Black](https://github.com/psf/black)

. . .

::: {.callout-tip}
- [Exemples d’erreurs repérées]{.blue2} par un _linter_ :
    + lignes de code trop longues ou mal indentées, parenthèses non équilibrées, noms de fonctions mal construits…
- [Exemples d’erreurs __non__ repérées]{.blue2} par un _linter_ :
    + fonctions mal utilisées, arguments mal spécifiés, structure du code incohérente, code insuffisamment documenté…
:::

## :two: Utiliser des fonctions {.smaller}

::: {.callout-important}
## Règle d'or

Il faut utiliser une [**fonction**]{.red2} dès qu'on utilise une même
portion de code plus de deux fois ([**_don't repeat yourself_ (DRY)**]{.red2})
:::

- [**Limite les risques d'erreurs**]{.orange} liés aux copier/coller
- Rend le code [**plus lisible**]{.orange} et [**plus compact**]{.orange}
- [**Un seul endroit**]{.orange} du code à modifier lorsqu'on souhaite modifier le traitement
- Facilite la [**réutilisation**]{.orange} et la [**documentation**]{.orange} du code !

. . .

::: {.callout-tip}
## Règles pour écrire des fonctions **pertinentes**

- Une tâche = une fonction
- Une tâche complexe = un enchaînement de fonctions réalisant chacune une tâche simple
- Limiter l'utilisation de variables globales.

:::

## :three: Documenter son code

- Documenter le [__pourquoi__]{.orange} plutôt que le [__comment__]{.orange}

- Privilégier l'[**auto-documentation**]{.orange} via des nommages pertinents

. . .

::: {.callout-tip}
## Comment bien documenter un script ?

- [**Minimum**]{.orange} 🚦 : décrire ce que le code fait au début du script
- [**Bien**]{.orange} 👍 : commenter les parties "délicates" du code
- [**Idéal**]{.orange} 💪 : documenter ses fonctions avec des *docstrings*
:::
